RoR/blog/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  get 'home/index'

  root 'home#index'

  get 'comments/:value' => 'comments#show'

end

RoR/blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

RoR/blog/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
end

RoR/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  http_basic_authenticate_with name: "boomingbrake", password: "secret"
end

RoR/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "boomingbrake", password: "secret", only: :destroy
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

RoR/blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

RoR/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: "boomingbrake", password: "secret", except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order('created_at DESC').limit(3);

    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @post }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :id)
    end
end

RoR/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

RoR/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

RoR/blog/app/helpers/home_helper.rb
module HomeHelper
end

RoR/blog/app/helpers/posts_helper.rb
module PostsHelper
end

RoR/blog/app/views/comments/_comment.html.erb
<section class="section__container">
  <p>
    <%= comment.body %>
  </p>
</section>
<%= link_to 'Delete', [comment.post, comment],
             method: :delete,
             data: { confirm: 'Are you sure?' } %>

RoR/blog/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
<section class="section__container">

<h2 class="section__head"></h2>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
</section>
<% end %>

RoR/blog/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

RoR/blog/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commenter</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

RoR/blog/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

RoR/blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

RoR/blog/app/views/home/index.html.erb
<h1 class="main__head">Daily Theme</h1>
<h2 class="main__head--sub">Reflection is Important.</h2>
<h2 class="main__head--sub">Be Conscious.</h2>
<h2 class="main__head--sub">Show Appreciation.</h2>
<p class="intro-text">
  I made it my personal goal to take time to capture the theme of
  each day. This is where you can come and read them.
</p>

<h2 class="main__head--sub"><u> <%= link_to "My Daily Themes", posts_path %> </u> </h2>

RoR/blog/app/views/layouts/_header.html.erb
<h1>HI</h1>
<h2><%= name %></h2>

RoR/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

</head>
<body>
<main class="main__container">
<%= yield %>
</main>
</body>
</html>

RoR/blog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RoR/blog/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

RoR/blog/app/views/posts/index.html.erb
<header>
  <%= render 'layouts/header2', {:name => 'bmoney'} %>
</header>
<p id="notice"><%= notice %></p>

<h1 class="main__head">Daily Themes</h1>

    <% @posts.each do |post| %>
      <section class="section__container">
        <h2 clas="section__head"><%= post.title %></h2>
        <p><%= post.content %></p>
        <%= link_to 'Show', post %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
      </section>
    <% end %>

<p>
  <%= link_to 'New Post', new_post_path %>
  <%= link_to 'Back', posts_path %>
</p>

RoR/blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

RoR/blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<h2 class="main__head--sub">
  <%= @post.title %>
</h2>

<h2 class="main__head--sub">
  <%= @post.content %>
</h2>

<div id="tabRight" class="tab right is-closed bounce">
      </div>
      <aside id="tabElementRight" class="tab__element right">

<h2 class="section__head">Comments</h2>
<%= render @post.comments %>
</section>

<h2 class="section__head">Add a comment:</h2>
<%= render 'comments/form' %>
</aside>




<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>